name: ml-deployment

# Controls when the action will run. 
on:
  push:
    branches:
      - master

jobs:
  workflow:
    name: Worflow that configures aws, setup dvs and run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install_dependencies
        run: |
          python -m pip install -r requirements.txt && \
          python -m pip install flake8
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Setup data version control
        uses: iterative/setup-dvc@v1
      - name: Pull data from DVC
        run: dvc pull
      - name: Run Flake8
        run: flake8
      - name: Run pytest
        run: pytest
